### PR TITLE
fix: jp auto servant level

### LINKED ISSUE #2053: Auto leveling is broken after 10th anniversary update in JP
### Preparation

- [x] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [x] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [x] I read the [Troubleshooting Guide](https://github.com/Fate-Grand-Automata/FGA/wiki/Troubleshooting)

### FGO server

JP

### FGA build number

2982

### Describe the bug

JP introduced a few new UI elements in the Servant Enhancement screen.

New "Clear" button in the top right and the Auto Select button was moved to the left.
Image

New Automatic Set toggle under the rarity selection, which automatically fills the 20 slots with Embers after the enhancement was done.
Image

They also added automatic CE leveling to this update.

Image
Image

### Video

https://github.com/user-attachments/assets/272d2f5f-6a11-4812-b8fa-75dadbe13f35

### Device model

Not specified

### Android version

15

### Screen size

_No response_

### RAM

_No response_

### PR DESCRIPTION
**Pull request by ArthurKun21**
- Fixes #2053

### CODE REVIEW

File: scripts/src/main/java/io/github/fate_grand_automata/scripts/entrypoints/AutoServantLevel.kt [hunk 1]
```diff
@@ -250,9 +267,43 @@ class AutoServantLevel @Inject constructor(
      * @see isAutoSelectVisible
      */
     private fun performAutoSelect() {
+        if (stateAutoFill) {
+            locations.enhancementClick.click()
+            0.5.seconds.wait()
+            val exist = locations.servant.finalConfirmRegion.exists(
+                image = images[Images.Ok],
+                timeout = 3.seconds,
```
Comment (reconman) [inline scripts/src/main/java/io/github/fate_grand_automata/scripts/entrypoints/AutoServantLevel.kt:275]: Which situation are you checking here that isn't checked by `isEmptyEmberOrQPDialogVisible()`?

File: scripts/src/main/java/io/github/fate_grand_automata/scripts/entrypoints/AutoServantLevel.kt [hunk 2]
```diff
@@ -250,9 +267,43 @@ class AutoServantLevel @Inject constructor(
      * @see isAutoSelectVisible
      */
     private fun performAutoSelect() {
+        if (stateAutoFill) {
+            locations.enhancementClick.click()
```
Comment (reconman) [inline scripts/src/main/java/io/github/fate_grand_automata/scripts/entrypoints/AutoServantLevel.kt:271]: This one clicks on Enhance but if there's no autofill it doesn't do that.

Isn't it a better to idea to combine the `performAutoSelect` and `performEnhancement` methods?

File: scripts/src/main/java/io/github/fate_grand_automata/scripts/entrypoints/AutoServantLevel.kt (hunk 1 above)
Comment (ArthurKun21) [reply scripts/src/main/java/io/github/fate_grand_automata/scripts/entrypoints/AutoServantLevel.kt:275]: When you ran out of embers, it doesn't show any dialog. This will let the app knows it has no more embers

**Review by reconman — COMMENTED** [review]
Added else for better readability
