### PR TITLE
Raid delay

### LINKED ISSUE #1720: Actions on turn 2 during raid battles inconsistent
### Preparation

- [X] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [X] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [X] I read the [Troubleshooting Guide](https://github.com/Fate-Grand-Automata/FGA/wiki/Troubleshooting)

### FGO server

NA

### FGA build number

2288

### Describe the bug

Often on the second turn of raids, FGA is for some reason unable to perform actions it's supposed to do and defaults to pressing the attack button. I believe this is due to to the popup showing 'thanks to masters, X number of raid boss has been killed' that messes up FGA's recognition of buttons that makes it panic. It seems to keep happening when I make it try to use plugsuit swap after the first turn of raids, but everything is affected, including using skills from servants in the third row. It sometimes works so it's not a problem with the inputted commands, like the difference between NP into next wave vs NP into same wave.

### Video

https://youtu.be/t4zOBwKIVFs

### Device model

Samsung galaxy tab s8

### Android version

12

### Screen size

2560 x 1600 

### RAM

8

### LINKED ISSUE #2160: 终章第六节柱子战中fga无法正常运行
### Preparation

- [x] I tested the [latest release](https://github.com/Fate-Grand-Automata/FGA/releases/tag/canary)
- [x] I looked at other issues (even the [closed ones](https://github.com/Fate-Grand-Automata/FGA/issues?q=is%3Aissue+is%3Aclosed))
- [x] I read the [Troubleshooting Guide](https://github.com/Fate-Grand-Automata/FGA/wiki/Troubleshooting)

### FGO server

JP

### FGA build number

3011

### Describe the bug

在终章第六节柱子战中，每回合都会弹出boos剩余的血量，fga会出错而不进行正常操作，会直接进入选卡界面进行随机选卡，而不是按要求使用技能

### Video

Image
Image

### Device model

iqoo z10

### Android version

15

### Screen size

_No response_

### RAM

24g

### PR DESCRIPTION
**Pull request by reconman**
# Raid delay

## Pull Request Type

- [ ] Bugfix
- [X] Feature Implementation
- [ ] Documentation
- [ ] Other

## Related issue

- fixes #1720
- fixes #2160

## Description

Current JP Raid have the same mechanics as the Tunguska. Where it shows the remaining kills which causes the script to unable to perform the next turn commands. This PR aims to add functionality to delay the before the turn starts to solved this problem.

## Screenshots 

image

### CODE REVIEW

File: app/src/main/java/io/github/fate_grand_automata/ui/battle_config_item/RaidDelay.kt [hunk 1]
```diff
@@ -0,0 +1,183 @@
...
+            .fillMaxHeight()
+            .clickable(
+                onClick = { dialog.show() }
+            )
+            .padding(8.dp, 5.dp),
+        horizontalAlignment = Alignment.CenterHorizontally,
+        verticalArrangement = Arrangement.Center
+    ) {
+        Text(
+            stringResource(R.string.p_battle_config_raid).uppercase(),
```
Comment (ArthurKun21) [inline app/src/main/java/io/github/fate_grand_automata/ui/battle_config_item/RaidDelay.kt]:
```suggestion
            stringResource(R.string.p_battle_config_raid_delay).uppercase(),
```

File: app/src/main/res/values/localized.xml [hunk 2]
```diff
@@ -480,4 +480,12 @@ After pressing on the button, switch the app filter from \"Not optimized\" to \"
     <string name="servant_enhancement_none_selected">No Servant Selected. Please select a Servant before proceeding.</string>
     <string name="servant_enhancement_aborted">Enhancement was aborted</string>
     <string name="note">"Note:"</string>
+
+    <string name="p_battle_config_raid">"Raid"</string>
+    <string name="p_battle_config_raid_delay">"Raid Delay"</string>
```
Comment (ArthurKun21) [inline app/src/main/res/values/localized.xml]:
```suggestion
    <string name="p_battle_config_raid_delay">"Raid Turn Delay"</string>
```

File: app/src/main/res/values/localized.xml [hunk 3]
```diff
@@ -480,4 +480,12 @@ After pressing on the button, switch the app filter from \"Not optimized\" to \"
     <string name="servant_enhancement_none_selected">No Servant Selected. Please select a Servant before proceeding.</string>
     <string name="servant_enhancement_aborted">Enhancement was aborted</string>
     <string name="note">"Note:"</string>
+
+    <string name="p_battle_config_raid">"Raid"</string>
```
Comment (ArthurKun21) [inline app/src/main/res/values/localized.xml]:
```suggestion
```

Comment (reconman) [reply app/src/main/res/values/localized.xml]: "Raid Delay" is too long for the UI.

I'm thinking of adding the animation skip settings to the Raid button so they're combined.

Or create a new Raid section in the battle config where you can configure the values directly instead of in a popup.
